# Form implementation generated from reading ui file 'simple_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(parent=Dialog)
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(parent=Dialog)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_name)
        self.txt_name = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_name.setObjectName("txt_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_name)
        self.lbl_age = QtWidgets.QLabel(parent=Dialog)
        self.lbl_age.setObjectName("lbl_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_age)
        self.spin_age = QtWidgets.QSpinBox(parent=Dialog)
        self.spin_age.setMinimum(1)
        self.spin_age.setMaximum(150)
        self.spin_age.setProperty("value", 20)
        self.spin_age.setObjectName("spin_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_age)
        self.lbl_gender = QtWidgets.QLabel(parent=Dialog)
        self.lbl_gender.setObjectName("lbl_gender")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_gender)
        self.combo_gender = QtWidgets.QComboBox(parent=Dialog)
        self.combo_gender.setObjectName("combo_gender")
        self.combo_gender.addItem("")
        self.combo_gender.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_gender)
        self.verticalLayout.addLayout(self.formLayout)
        self.txt_info = QtWidgets.QTextEdit(parent=Dialog)
        self.txt_info.setReadOnly(True)
        self.txt_info.setObjectName("txt_info")
        self.verticalLayout.addWidget(self.txt_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_show = QtWidgets.QPushButton(parent=Dialog)
        self.btn_show.setObjectName("btn_show")
        self.horizontalLayout.addWidget(self.btn_show)
        self.btn_clear = QtWidgets.QPushButton(parent=Dialog)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)
        self.btn_close = QtWidgets.QPushButton(parent=Dialog)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "简单对话框示例"))
        self.lbl_title.setText(_translate("Dialog", "用户信息输入"))
        self.lbl_name.setText(_translate("Dialog", "姓名:"))
        self.txt_name.setPlaceholderText(_translate("Dialog", "请输入姓名"))
        self.lbl_age.setText(_translate("Dialog", "年龄:"))
        self.lbl_gender.setText(_translate("Dialog", "性别:"))
        self.combo_gender.setItemText(0, _translate("Dialog", "男"))
        self.combo_gender.setItemText(1, _translate("Dialog", "女"))
        self.txt_info.setPlaceholderText(_translate("Dialog", "这里会显示输入的信息..."))
        self.btn_show.setText(_translate("Dialog", "显示信息"))
        self.btn_clear.setText(_translate("Dialog", "清空"))
        self.btn_close.setText(_translate("Dialog", "关闭"))
